//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaoconN.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UsuarioDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomicilioField;
        
        private System.Nullable<System.DateTime> FechaRegField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Domicilio {
            get {
                return this.DomicilioField;
            }
            set {
                if ((object.ReferenceEquals(this.DomicilioField, value) != true)) {
                    this.DomicilioField = value;
                    this.RaisePropertyChanged("Domicilio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> FechaReg {
            get {
                return this.FechaRegField;
            }
            set {
                if ((this.FechaRegField.Equals(value) != true)) {
                    this.FechaRegField = value;
                    this.RaisePropertyChanged("FechaReg");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductoDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreZapatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionZapatoField;
        
        private System.Nullable<decimal> PrecioZapatoField;
        
        private System.Nullable<int> IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TallaZapatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorZapatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaterialZapatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlImagenField;
        
        private System.Nullable<int> StockZapatoField;
        
        private System.Nullable<System.DateTime> FechaAltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarcaZapatoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreZapato {
            get {
                return this.NombreZapatoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreZapatoField, value) != true)) {
                    this.NombreZapatoField = value;
                    this.RaisePropertyChanged("NombreZapato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DescripcionZapato {
            get {
                return this.DescripcionZapatoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionZapatoField, value) != true)) {
                    this.DescripcionZapatoField = value;
                    this.RaisePropertyChanged("DescripcionZapato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> PrecioZapato {
            get {
                return this.PrecioZapatoField;
            }
            set {
                if ((this.PrecioZapatoField.Equals(value) != true)) {
                    this.PrecioZapatoField = value;
                    this.RaisePropertyChanged("PrecioZapato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TallaZapato {
            get {
                return this.TallaZapatoField;
            }
            set {
                if ((object.ReferenceEquals(this.TallaZapatoField, value) != true)) {
                    this.TallaZapatoField = value;
                    this.RaisePropertyChanged("TallaZapato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ColorZapato {
            get {
                return this.ColorZapatoField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorZapatoField, value) != true)) {
                    this.ColorZapatoField = value;
                    this.RaisePropertyChanged("ColorZapato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string MaterialZapato {
            get {
                return this.MaterialZapatoField;
            }
            set {
                if ((object.ReferenceEquals(this.MaterialZapatoField, value) != true)) {
                    this.MaterialZapatoField = value;
                    this.RaisePropertyChanged("MaterialZapato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string UrlImagen {
            get {
                return this.UrlImagenField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlImagenField, value) != true)) {
                    this.UrlImagenField = value;
                    this.RaisePropertyChanged("UrlImagen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> StockZapato {
            get {
                return this.StockZapatoField;
            }
            set {
                if ((this.StockZapatoField.Equals(value) != true)) {
                    this.StockZapatoField = value;
                    this.RaisePropertyChanged("StockZapato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> FechaAlta {
            get {
                return this.FechaAltaField;
            }
            set {
                if ((this.FechaAltaField.Equals(value) != true)) {
                    this.FechaAltaField = value;
                    this.RaisePropertyChanged("FechaAlta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MarcaZapato {
            get {
                return this.MarcaZapatoField;
            }
            set {
                if ((object.ReferenceEquals(this.MarcaZapatoField, value) != true)) {
                    this.MarcaZapatoField = value;
                    this.RaisePropertyChanged("MarcaZapato");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CategoriaDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionCategoriaField;
        
        private System.Nullable<int> IdPadreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreCategoria {
            get {
                return this.NombreCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCategoriaField, value) != true)) {
                    this.NombreCategoriaField = value;
                    this.RaisePropertyChanged("NombreCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DescripcionCategoria {
            get {
                return this.DescripcionCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionCategoriaField, value) != true)) {
                    this.DescripcionCategoriaField = value;
                    this.RaisePropertyChanged("DescripcionCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> IdPadre {
            get {
                return this.IdPadreField;
            }
            set {
                if ((this.IdPadreField.Equals(value) != true)) {
                    this.IdPadreField = value;
                    this.RaisePropertyChanged("IdPadre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.TiendaServicioSoap")]
    public interface TiendaServicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerListaUsuariosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaUsuarios", ReplyAction="*")]
        MaoconN.ServiceReference1.ObtenerListaUsuariosResponse ObtenerListaUsuarios(MaoconN.ServiceReference1.ObtenerListaUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaUsuariosResponse> ObtenerListaUsuariosAsync(MaoconN.ServiceReference1.ObtenerListaUsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarUsuarioPorIDResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuarioPorID", ReplyAction="*")]
        MaoconN.ServiceReference1.BuscarUsuarioPorIDResponse BuscarUsuarioPorID(MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuarioPorID", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.BuscarUsuarioPorIDResponse> BuscarUsuarioPorIDAsync(MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoUsuario", ReplyAction="*")]
        MaoconN.ServiceReference1.AgregarNuevoUsuarioResponse AgregarNuevoUsuario(MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.AgregarNuevoUsuarioResponse> AgregarNuevoUsuarioAsync(MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        MaoconN.ServiceReference1.ActualizarUsuarioResponse ActualizarUsuario(MaoconN.ServiceReference1.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ActualizarUsuarioResponse> ActualizarUsuarioAsync(MaoconN.ServiceReference1.ActualizarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        bool EliminarUsuario(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerListaProductosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaProductos", ReplyAction="*")]
        MaoconN.ServiceReference1.ObtenerListaProductosResponse ObtenerListaProductos(MaoconN.ServiceReference1.ObtenerListaProductosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaProductos", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaProductosResponse> ObtenerListaProductosAsync(MaoconN.ServiceReference1.ObtenerListaProductosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento BuscarProductoPorIDResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarProductoPorID", ReplyAction="*")]
        MaoconN.ServiceReference1.BuscarProductoPorIDResponse BuscarProductoPorID(MaoconN.ServiceReference1.BuscarProductoPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarProductoPorID", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.BuscarProductoPorIDResponse> BuscarProductoPorIDAsync(MaoconN.ServiceReference1.BuscarProductoPorIDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoProducto", ReplyAction="*")]
        MaoconN.ServiceReference1.AgregarNuevoProductoResponse AgregarNuevoProducto(MaoconN.ServiceReference1.AgregarNuevoProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarNuevoProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.AgregarNuevoProductoResponse> AgregarNuevoProductoAsync(MaoconN.ServiceReference1.AgregarNuevoProductoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento producto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        MaoconN.ServiceReference1.ActualizarProductoResponse ActualizarProducto(MaoconN.ServiceReference1.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ActualizarProductoResponse> ActualizarProductoAsync(MaoconN.ServiceReference1.ActualizarProductoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        bool EliminarProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarProducto", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> EliminarProductoAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerListaCategoriasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaCategorias", ReplyAction="*")]
        MaoconN.ServiceReference1.ObtenerListaCategoriasResponse ObtenerListaCategorias(MaoconN.ServiceReference1.ObtenerListaCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerListaCategorias", ReplyAction="*")]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaCategoriasResponse> ObtenerListaCategoriasAsync(MaoconN.ServiceReference1.ObtenerListaCategoriasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ObtenerListaUsuariosRequestBody Body;
        
        public ObtenerListaUsuariosRequest() {
        }
        
        public ObtenerListaUsuariosRequest(MaoconN.ServiceReference1.ObtenerListaUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerListaUsuariosRequestBody {
        
        public ObtenerListaUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ObtenerListaUsuariosResponseBody Body;
        
        public ObtenerListaUsuariosResponse() {
        }
        
        public ObtenerListaUsuariosResponse(MaoconN.ServiceReference1.ObtenerListaUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerListaUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.UsuarioDTO[] ObtenerListaUsuariosResult;
        
        public ObtenerListaUsuariosResponseBody() {
        }
        
        public ObtenerListaUsuariosResponseBody(MaoconN.ServiceReference1.UsuarioDTO[] ObtenerListaUsuariosResult) {
            this.ObtenerListaUsuariosResult = ObtenerListaUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUsuarioPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUsuarioPorID", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.BuscarUsuarioPorIDRequestBody Body;
        
        public BuscarUsuarioPorIDRequest() {
        }
        
        public BuscarUsuarioPorIDRequest(MaoconN.ServiceReference1.BuscarUsuarioPorIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioPorIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarUsuarioPorIDRequestBody() {
        }
        
        public BuscarUsuarioPorIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUsuarioPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUsuarioPorIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.BuscarUsuarioPorIDResponseBody Body;
        
        public BuscarUsuarioPorIDResponse() {
        }
        
        public BuscarUsuarioPorIDResponse(MaoconN.ServiceReference1.BuscarUsuarioPorIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioPorIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.UsuarioDTO BuscarUsuarioPorIDResult;
        
        public BuscarUsuarioPorIDResponseBody() {
        }
        
        public BuscarUsuarioPorIDResponseBody(MaoconN.ServiceReference1.UsuarioDTO BuscarUsuarioPorIDResult) {
            this.BuscarUsuarioPorIDResult = BuscarUsuarioPorIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoUsuario", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.AgregarNuevoUsuarioRequestBody Body;
        
        public AgregarNuevoUsuarioRequest() {
        }
        
        public AgregarNuevoUsuarioRequest(MaoconN.ServiceReference1.AgregarNuevoUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.UsuarioDTO usuario;
        
        public AgregarNuevoUsuarioRequestBody() {
        }
        
        public AgregarNuevoUsuarioRequestBody(MaoconN.ServiceReference1.UsuarioDTO usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.AgregarNuevoUsuarioResponseBody Body;
        
        public AgregarNuevoUsuarioResponse() {
        }
        
        public AgregarNuevoUsuarioResponse(MaoconN.ServiceReference1.AgregarNuevoUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarNuevoUsuarioResult;
        
        public AgregarNuevoUsuarioResponseBody() {
        }
        
        public AgregarNuevoUsuarioResponseBody(bool AgregarNuevoUsuarioResult) {
            this.AgregarNuevoUsuarioResult = AgregarNuevoUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ActualizarUsuarioRequestBody Body;
        
        public ActualizarUsuarioRequest() {
        }
        
        public ActualizarUsuarioRequest(MaoconN.ServiceReference1.ActualizarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.UsuarioDTO usuario;
        
        public ActualizarUsuarioRequestBody() {
        }
        
        public ActualizarUsuarioRequestBody(MaoconN.ServiceReference1.UsuarioDTO usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ActualizarUsuarioResponseBody Body;
        
        public ActualizarUsuarioResponse() {
        }
        
        public ActualizarUsuarioResponse(MaoconN.ServiceReference1.ActualizarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarUsuarioResult;
        
        public ActualizarUsuarioResponseBody() {
        }
        
        public ActualizarUsuarioResponseBody(bool ActualizarUsuarioResult) {
            this.ActualizarUsuarioResult = ActualizarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaProductosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaProductos", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ObtenerListaProductosRequestBody Body;
        
        public ObtenerListaProductosRequest() {
        }
        
        public ObtenerListaProductosRequest(MaoconN.ServiceReference1.ObtenerListaProductosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerListaProductosRequestBody {
        
        public ObtenerListaProductosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaProductosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaProductosResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ObtenerListaProductosResponseBody Body;
        
        public ObtenerListaProductosResponse() {
        }
        
        public ObtenerListaProductosResponse(MaoconN.ServiceReference1.ObtenerListaProductosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerListaProductosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.ProductoDTO[] ObtenerListaProductosResult;
        
        public ObtenerListaProductosResponseBody() {
        }
        
        public ObtenerListaProductosResponseBody(MaoconN.ServiceReference1.ProductoDTO[] ObtenerListaProductosResult) {
            this.ObtenerListaProductosResult = ObtenerListaProductosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarProductoPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarProductoPorID", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.BuscarProductoPorIDRequestBody Body;
        
        public BuscarProductoPorIDRequest() {
        }
        
        public BuscarProductoPorIDRequest(MaoconN.ServiceReference1.BuscarProductoPorIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarProductoPorIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public BuscarProductoPorIDRequestBody() {
        }
        
        public BuscarProductoPorIDRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarProductoPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarProductoPorIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.BuscarProductoPorIDResponseBody Body;
        
        public BuscarProductoPorIDResponse() {
        }
        
        public BuscarProductoPorIDResponse(MaoconN.ServiceReference1.BuscarProductoPorIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarProductoPorIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.ProductoDTO BuscarProductoPorIDResult;
        
        public BuscarProductoPorIDResponseBody() {
        }
        
        public BuscarProductoPorIDResponseBody(MaoconN.ServiceReference1.ProductoDTO BuscarProductoPorIDResult) {
            this.BuscarProductoPorIDResult = BuscarProductoPorIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoProducto", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.AgregarNuevoProductoRequestBody Body;
        
        public AgregarNuevoProductoRequest() {
        }
        
        public AgregarNuevoProductoRequest(MaoconN.ServiceReference1.AgregarNuevoProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.ProductoDTO producto;
        
        public AgregarNuevoProductoRequestBody() {
        }
        
        public AgregarNuevoProductoRequestBody(MaoconN.ServiceReference1.ProductoDTO producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarNuevoProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarNuevoProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.AgregarNuevoProductoResponseBody Body;
        
        public AgregarNuevoProductoResponse() {
        }
        
        public AgregarNuevoProductoResponse(MaoconN.ServiceReference1.AgregarNuevoProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarNuevoProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AgregarNuevoProductoResult;
        
        public AgregarNuevoProductoResponseBody() {
        }
        
        public AgregarNuevoProductoResponseBody(bool AgregarNuevoProductoResult) {
            this.AgregarNuevoProductoResult = AgregarNuevoProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProducto", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ActualizarProductoRequestBody Body;
        
        public ActualizarProductoRequest() {
        }
        
        public ActualizarProductoRequest(MaoconN.ServiceReference1.ActualizarProductoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.ProductoDTO producto;
        
        public ActualizarProductoRequestBody() {
        }
        
        public ActualizarProductoRequestBody(MaoconN.ServiceReference1.ProductoDTO producto) {
            this.producto = producto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarProductoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarProductoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ActualizarProductoResponseBody Body;
        
        public ActualizarProductoResponse() {
        }
        
        public ActualizarProductoResponse(MaoconN.ServiceReference1.ActualizarProductoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarProductoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActualizarProductoResult;
        
        public ActualizarProductoResponseBody() {
        }
        
        public ActualizarProductoResponseBody(bool ActualizarProductoResult) {
            this.ActualizarProductoResult = ActualizarProductoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaCategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaCategorias", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ObtenerListaCategoriasRequestBody Body;
        
        public ObtenerListaCategoriasRequest() {
        }
        
        public ObtenerListaCategoriasRequest(MaoconN.ServiceReference1.ObtenerListaCategoriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerListaCategoriasRequestBody {
        
        public ObtenerListaCategoriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerListaCategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerListaCategoriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public MaoconN.ServiceReference1.ObtenerListaCategoriasResponseBody Body;
        
        public ObtenerListaCategoriasResponse() {
        }
        
        public ObtenerListaCategoriasResponse(MaoconN.ServiceReference1.ObtenerListaCategoriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerListaCategoriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MaoconN.ServiceReference1.CategoriaDTO[] ObtenerListaCategoriasResult;
        
        public ObtenerListaCategoriasResponseBody() {
        }
        
        public ObtenerListaCategoriasResponseBody(MaoconN.ServiceReference1.CategoriaDTO[] ObtenerListaCategoriasResult) {
            this.ObtenerListaCategoriasResult = ObtenerListaCategoriasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TiendaServicioSoapChannel : MaoconN.ServiceReference1.TiendaServicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiendaServicioSoapClient : System.ServiceModel.ClientBase<MaoconN.ServiceReference1.TiendaServicioSoap>, MaoconN.ServiceReference1.TiendaServicioSoap {
        
        public TiendaServicioSoapClient() {
        }
        
        public TiendaServicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TiendaServicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiendaServicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TiendaServicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.ObtenerListaUsuariosResponse MaoconN.ServiceReference1.TiendaServicioSoap.ObtenerListaUsuarios(MaoconN.ServiceReference1.ObtenerListaUsuariosRequest request) {
            return base.Channel.ObtenerListaUsuarios(request);
        }
        
        public MaoconN.ServiceReference1.UsuarioDTO[] ObtenerListaUsuarios() {
            MaoconN.ServiceReference1.ObtenerListaUsuariosRequest inValue = new MaoconN.ServiceReference1.ObtenerListaUsuariosRequest();
            inValue.Body = new MaoconN.ServiceReference1.ObtenerListaUsuariosRequestBody();
            MaoconN.ServiceReference1.ObtenerListaUsuariosResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ObtenerListaUsuarios(inValue);
            return retVal.Body.ObtenerListaUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaUsuariosResponse> MaoconN.ServiceReference1.TiendaServicioSoap.ObtenerListaUsuariosAsync(MaoconN.ServiceReference1.ObtenerListaUsuariosRequest request) {
            return base.Channel.ObtenerListaUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaUsuariosResponse> ObtenerListaUsuariosAsync() {
            MaoconN.ServiceReference1.ObtenerListaUsuariosRequest inValue = new MaoconN.ServiceReference1.ObtenerListaUsuariosRequest();
            inValue.Body = new MaoconN.ServiceReference1.ObtenerListaUsuariosRequestBody();
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ObtenerListaUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.BuscarUsuarioPorIDResponse MaoconN.ServiceReference1.TiendaServicioSoap.BuscarUsuarioPorID(MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest request) {
            return base.Channel.BuscarUsuarioPorID(request);
        }
        
        public MaoconN.ServiceReference1.UsuarioDTO BuscarUsuarioPorID(int id) {
            MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest inValue = new MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest();
            inValue.Body = new MaoconN.ServiceReference1.BuscarUsuarioPorIDRequestBody();
            inValue.Body.id = id;
            MaoconN.ServiceReference1.BuscarUsuarioPorIDResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).BuscarUsuarioPorID(inValue);
            return retVal.Body.BuscarUsuarioPorIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.BuscarUsuarioPorIDResponse> MaoconN.ServiceReference1.TiendaServicioSoap.BuscarUsuarioPorIDAsync(MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest request) {
            return base.Channel.BuscarUsuarioPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.BuscarUsuarioPorIDResponse> BuscarUsuarioPorIDAsync(int id) {
            MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest inValue = new MaoconN.ServiceReference1.BuscarUsuarioPorIDRequest();
            inValue.Body = new MaoconN.ServiceReference1.BuscarUsuarioPorIDRequestBody();
            inValue.Body.id = id;
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).BuscarUsuarioPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.AgregarNuevoUsuarioResponse MaoconN.ServiceReference1.TiendaServicioSoap.AgregarNuevoUsuario(MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest request) {
            return base.Channel.AgregarNuevoUsuario(request);
        }
        
        public bool AgregarNuevoUsuario(MaoconN.ServiceReference1.UsuarioDTO usuario) {
            MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest inValue = new MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest();
            inValue.Body = new MaoconN.ServiceReference1.AgregarNuevoUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            MaoconN.ServiceReference1.AgregarNuevoUsuarioResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).AgregarNuevoUsuario(inValue);
            return retVal.Body.AgregarNuevoUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.AgregarNuevoUsuarioResponse> MaoconN.ServiceReference1.TiendaServicioSoap.AgregarNuevoUsuarioAsync(MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest request) {
            return base.Channel.AgregarNuevoUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.AgregarNuevoUsuarioResponse> AgregarNuevoUsuarioAsync(MaoconN.ServiceReference1.UsuarioDTO usuario) {
            MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest inValue = new MaoconN.ServiceReference1.AgregarNuevoUsuarioRequest();
            inValue.Body = new MaoconN.ServiceReference1.AgregarNuevoUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).AgregarNuevoUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.ActualizarUsuarioResponse MaoconN.ServiceReference1.TiendaServicioSoap.ActualizarUsuario(MaoconN.ServiceReference1.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuario(request);
        }
        
        public bool ActualizarUsuario(MaoconN.ServiceReference1.UsuarioDTO usuario) {
            MaoconN.ServiceReference1.ActualizarUsuarioRequest inValue = new MaoconN.ServiceReference1.ActualizarUsuarioRequest();
            inValue.Body = new MaoconN.ServiceReference1.ActualizarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            MaoconN.ServiceReference1.ActualizarUsuarioResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ActualizarUsuario(inValue);
            return retVal.Body.ActualizarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ActualizarUsuarioResponse> MaoconN.ServiceReference1.TiendaServicioSoap.ActualizarUsuarioAsync(MaoconN.ServiceReference1.ActualizarUsuarioRequest request) {
            return base.Channel.ActualizarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.ActualizarUsuarioResponse> ActualizarUsuarioAsync(MaoconN.ServiceReference1.UsuarioDTO usuario) {
            MaoconN.ServiceReference1.ActualizarUsuarioRequest inValue = new MaoconN.ServiceReference1.ActualizarUsuarioRequest();
            inValue.Body = new MaoconN.ServiceReference1.ActualizarUsuarioRequestBody();
            inValue.Body.usuario = usuario;
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ActualizarUsuarioAsync(inValue);
        }
        
        public bool EliminarUsuario(int id) {
            return base.Channel.EliminarUsuario(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id) {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.ObtenerListaProductosResponse MaoconN.ServiceReference1.TiendaServicioSoap.ObtenerListaProductos(MaoconN.ServiceReference1.ObtenerListaProductosRequest request) {
            return base.Channel.ObtenerListaProductos(request);
        }
        
        public MaoconN.ServiceReference1.ProductoDTO[] ObtenerListaProductos() {
            MaoconN.ServiceReference1.ObtenerListaProductosRequest inValue = new MaoconN.ServiceReference1.ObtenerListaProductosRequest();
            inValue.Body = new MaoconN.ServiceReference1.ObtenerListaProductosRequestBody();
            MaoconN.ServiceReference1.ObtenerListaProductosResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ObtenerListaProductos(inValue);
            return retVal.Body.ObtenerListaProductosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaProductosResponse> MaoconN.ServiceReference1.TiendaServicioSoap.ObtenerListaProductosAsync(MaoconN.ServiceReference1.ObtenerListaProductosRequest request) {
            return base.Channel.ObtenerListaProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaProductosResponse> ObtenerListaProductosAsync() {
            MaoconN.ServiceReference1.ObtenerListaProductosRequest inValue = new MaoconN.ServiceReference1.ObtenerListaProductosRequest();
            inValue.Body = new MaoconN.ServiceReference1.ObtenerListaProductosRequestBody();
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ObtenerListaProductosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.BuscarProductoPorIDResponse MaoconN.ServiceReference1.TiendaServicioSoap.BuscarProductoPorID(MaoconN.ServiceReference1.BuscarProductoPorIDRequest request) {
            return base.Channel.BuscarProductoPorID(request);
        }
        
        public MaoconN.ServiceReference1.ProductoDTO BuscarProductoPorID(int id) {
            MaoconN.ServiceReference1.BuscarProductoPorIDRequest inValue = new MaoconN.ServiceReference1.BuscarProductoPorIDRequest();
            inValue.Body = new MaoconN.ServiceReference1.BuscarProductoPorIDRequestBody();
            inValue.Body.id = id;
            MaoconN.ServiceReference1.BuscarProductoPorIDResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).BuscarProductoPorID(inValue);
            return retVal.Body.BuscarProductoPorIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.BuscarProductoPorIDResponse> MaoconN.ServiceReference1.TiendaServicioSoap.BuscarProductoPorIDAsync(MaoconN.ServiceReference1.BuscarProductoPorIDRequest request) {
            return base.Channel.BuscarProductoPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.BuscarProductoPorIDResponse> BuscarProductoPorIDAsync(int id) {
            MaoconN.ServiceReference1.BuscarProductoPorIDRequest inValue = new MaoconN.ServiceReference1.BuscarProductoPorIDRequest();
            inValue.Body = new MaoconN.ServiceReference1.BuscarProductoPorIDRequestBody();
            inValue.Body.id = id;
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).BuscarProductoPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.AgregarNuevoProductoResponse MaoconN.ServiceReference1.TiendaServicioSoap.AgregarNuevoProducto(MaoconN.ServiceReference1.AgregarNuevoProductoRequest request) {
            return base.Channel.AgregarNuevoProducto(request);
        }
        
        public bool AgregarNuevoProducto(MaoconN.ServiceReference1.ProductoDTO producto) {
            MaoconN.ServiceReference1.AgregarNuevoProductoRequest inValue = new MaoconN.ServiceReference1.AgregarNuevoProductoRequest();
            inValue.Body = new MaoconN.ServiceReference1.AgregarNuevoProductoRequestBody();
            inValue.Body.producto = producto;
            MaoconN.ServiceReference1.AgregarNuevoProductoResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).AgregarNuevoProducto(inValue);
            return retVal.Body.AgregarNuevoProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.AgregarNuevoProductoResponse> MaoconN.ServiceReference1.TiendaServicioSoap.AgregarNuevoProductoAsync(MaoconN.ServiceReference1.AgregarNuevoProductoRequest request) {
            return base.Channel.AgregarNuevoProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.AgregarNuevoProductoResponse> AgregarNuevoProductoAsync(MaoconN.ServiceReference1.ProductoDTO producto) {
            MaoconN.ServiceReference1.AgregarNuevoProductoRequest inValue = new MaoconN.ServiceReference1.AgregarNuevoProductoRequest();
            inValue.Body = new MaoconN.ServiceReference1.AgregarNuevoProductoRequestBody();
            inValue.Body.producto = producto;
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).AgregarNuevoProductoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.ActualizarProductoResponse MaoconN.ServiceReference1.TiendaServicioSoap.ActualizarProducto(MaoconN.ServiceReference1.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProducto(request);
        }
        
        public bool ActualizarProducto(MaoconN.ServiceReference1.ProductoDTO producto) {
            MaoconN.ServiceReference1.ActualizarProductoRequest inValue = new MaoconN.ServiceReference1.ActualizarProductoRequest();
            inValue.Body = new MaoconN.ServiceReference1.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            MaoconN.ServiceReference1.ActualizarProductoResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ActualizarProducto(inValue);
            return retVal.Body.ActualizarProductoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ActualizarProductoResponse> MaoconN.ServiceReference1.TiendaServicioSoap.ActualizarProductoAsync(MaoconN.ServiceReference1.ActualizarProductoRequest request) {
            return base.Channel.ActualizarProductoAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.ActualizarProductoResponse> ActualizarProductoAsync(MaoconN.ServiceReference1.ProductoDTO producto) {
            MaoconN.ServiceReference1.ActualizarProductoRequest inValue = new MaoconN.ServiceReference1.ActualizarProductoRequest();
            inValue.Body = new MaoconN.ServiceReference1.ActualizarProductoRequestBody();
            inValue.Body.producto = producto;
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ActualizarProductoAsync(inValue);
        }
        
        public bool EliminarProducto(int id) {
            return base.Channel.EliminarProducto(id);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProductoAsync(int id) {
            return base.Channel.EliminarProductoAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MaoconN.ServiceReference1.ObtenerListaCategoriasResponse MaoconN.ServiceReference1.TiendaServicioSoap.ObtenerListaCategorias(MaoconN.ServiceReference1.ObtenerListaCategoriasRequest request) {
            return base.Channel.ObtenerListaCategorias(request);
        }
        
        public MaoconN.ServiceReference1.CategoriaDTO[] ObtenerListaCategorias() {
            MaoconN.ServiceReference1.ObtenerListaCategoriasRequest inValue = new MaoconN.ServiceReference1.ObtenerListaCategoriasRequest();
            inValue.Body = new MaoconN.ServiceReference1.ObtenerListaCategoriasRequestBody();
            MaoconN.ServiceReference1.ObtenerListaCategoriasResponse retVal = ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ObtenerListaCategorias(inValue);
            return retVal.Body.ObtenerListaCategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaCategoriasResponse> MaoconN.ServiceReference1.TiendaServicioSoap.ObtenerListaCategoriasAsync(MaoconN.ServiceReference1.ObtenerListaCategoriasRequest request) {
            return base.Channel.ObtenerListaCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<MaoconN.ServiceReference1.ObtenerListaCategoriasResponse> ObtenerListaCategoriasAsync() {
            MaoconN.ServiceReference1.ObtenerListaCategoriasRequest inValue = new MaoconN.ServiceReference1.ObtenerListaCategoriasRequest();
            inValue.Body = new MaoconN.ServiceReference1.ObtenerListaCategoriasRequestBody();
            return ((MaoconN.ServiceReference1.TiendaServicioSoap)(this)).ObtenerListaCategoriasAsync(inValue);
        }
    }
}
