//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComentariosValoraciones
    {
        public int id_coment { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_prod { get; set; }
        public string comentario { get; set; }
        public Nullable<int> valor { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
