//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Productos()
        {
            this.ComentariosValoraciones = new HashSet<ComentariosValoraciones>();
            this.DetalleCarrito = new HashSet<DetalleCarrito>();
        }
    
        public int id_producto { get; set; }
        public string nombre_zapato { get; set; }
        public string descripcion_zapato { get; set; }
        public Nullable<decimal> precio_zapato { get; set; }
        public Nullable<int> id_cat { get; set; }
        public string talla_zap { get; set; }
        public string color_zap { get; set; }
        public string material_zap { get; set; }
        public string url_img { get; set; }
        public Nullable<int> stock_zap { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
        public string marca_zap { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComentariosValoraciones> ComentariosValoraciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleCarrito> DetalleCarrito { get; set; }
    }
}
